/**
 * contracts/presets.ts
 * ─────────────────────────────────────────────────────────────
 * Bộ bài mặc định theo số người (4–8). Khớp ROLE_PRESETS ở FE.
 */
import { ROLE, type Role } from './roles.js';

export const ROLE_PRESETS: Record<number, Role[]> = {
  4: [ROLE.WEREWOLF, ROLE.SEER, ROLE.VILLAGER, ROLE.VILLAGER],
  5: [ROLE.WEREWOLF, ROLE.SEER, ROLE.GUARD, ROLE.VILLAGER, ROLE.VILLAGER],
  6: [ROLE.WEREWOLF, ROLE.WEREWOLF, ROLE.SEER, ROLE.GUARD, ROLE.VILLAGER, ROLE.VILLAGER],
  7: [ROLE.WEREWOLF, ROLE.WEREWOLF, ROLE.SEER, ROLE.GUARD, ROLE.WITCH, ROLE.VILLAGER, ROLE.VILLAGER],
  8: [
    ROLE.WEREWOLF, ROLE.WEREWOLF, ROLE.SEER, ROLE.GUARD, ROLE.WITCH,
    ROLE.VILLAGER, ROLE.VILLAGER, ROLE.VILLAGER,
  ],
  9: [
    ROLE.WEREWOLF, ROLE.WEREWOLF, ROLE.WEREWOLF, ROLE.SEER, ROLE.GUARD, ROLE.WITCH,
    ROLE.VILLAGER, ROLE.VILLAGER, ROLE.VILLAGER,
  ],
  10: [
    ROLE.WEREWOLF, ROLE.WEREWOLF, ROLE.WEREWOLF, ROLE.SEER, ROLE.GUARD, ROLE.WITCH,
    ROLE.VILLAGER, ROLE.VILLAGER, ROLE.VILLAGER, ROLE.VILLAGER,
  ],
  11: [
    ROLE.WEREWOLF, ROLE.WEREWOLF, ROLE.WEREWOLF, ROLE.SEER, ROLE.GUARD, ROLE.WITCH,
    ROLE.VILLAGER, ROLE.VILLAGER, ROLE.VILLAGER, ROLE.VILLAGER, ROLE.VILLAGER,
  ],
  12: [
    ROLE.WEREWOLF, ROLE.WEREWOLF, ROLE.WEREWOLF, ROLE.SEER, ROLE.GUARD, ROLE.WITCH,
    ROLE.VILLAGER, ROLE.VILLAGER, ROLE.VILLAGER, ROLE.VILLAGER, ROLE.VILLAGER, ROLE.VILLAGER,
  ],
};
